### ISSUE TITLE
WikiProject dropdown

### ISSUE THREAD

**Issue by owcz** [harej/requestoid#4]
Feature request (are these useful? I have more, if you want)

Have the WikiProjects autocomplete or use a dropdown. Even better would be to use Wikidata to ask what type of "thing" the subject is and then to automatically associate those things with projects (for instance, type "film" or "movie" should associate with the film WikiProject)

**Comment by harej** [comment]
I do appreciate feature requests.

Now tracking this request on Phabricator: https://phabricator.wikimedia.org/T137042

For requests involving articles that already exist the request inherits a list of WikiProjects from the article's talk page. For requests for new articles this is not the case. I am intrigued by the idea of connecting requests to a Wikidata entry (or at least something using its ontology) but I am not sure how that would work since I am not aware of any connection between Wikidata items and WikiProjects.

**Comment by owcz** [comment]
Ah, didn't know you were using Phabricator—I'm okay with moving this discussion there
